language: node_js
node_js:
- 7.3.0
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - xvfb
    - libgnome-keyring-dev
env: CXX=g++-4.8
before_install: npm install -g grunt-cli
services: mongodb
deploy:
  provider: heroku
  app: hanno-oskar
  api_key:
    secure: Jf8YdNKE9LUiTSOCbOAhmFCE+euSiV4StnWOiQA8mTBMwuQKDDVaC9YdoTQAfrErXtSjN+gopN2WyFjqNlYGOSTUKKXAxK3FzVITkcnq0xbtJNJA3Lc38HIJMULCNRgXLBC+lnpIRQ88107fTfh27VJg01gbljO/7eii6k89dl6y1nQaEURSeuYJ8HOqrBNV3rMSZ5epQZahGxSMmZrGzCd87EMsDt/bDaJFcpoREQ5ELqXvQz4C7cpIdRgKK4+xtZxTW1qTuachIaa60XdAUdjUFJ/nenocjq2i2aLkXPLQJLlFe+9wOHgrxK4fzXdT3Y1eSK7bdpkrEu98evJZlLobESCx+kLK5nJNnw0SWtwqiynIfJl+y2mArcFSuxAxQUkZPWAXaLjYt6GNyVayKINi/ratvOOCeWdYe0IoVXIjyzPrl5/in3yjwGWUX3d7/JkJy/e1NXQP6DT4yQ1ArFGWEB1cB85tOBeSiqd18eL/42r3c+HuiKh8C9sxI/D+JMGWh7kC6roRyozESt57t1KP6gGto3nT4n2DlnmomvWV0cwvid0inJ4ki0r8nixvDEtnUIlvqVTc0X28bh0ZpnwGkvdPj7jZmAQFcfc/43gE2/JF4oGHOV3EbMQLgQUzDahGrWvqlSp95c/5cnNE1WhdFfR6nCf0ZSWdCvlY0qc=
