language: node_js
node_js:
- '0.12'
before_install: npm install -g grunt-cli
services: mongodb
deploy:
  provider: heroku
  app: hanno-oskar
  api_key:
    secure: TB+vB1ILxKR/1iSpWI49MU3Uxti4JvXOs5URkWkFV0Gie8pGWbIgHHo1ZXh7fUpOYw1m3p0plQdl6iNNYGChOgSOb8Lbn3/2q829dc/6Jc5NjvA1nsB+VFf6XTqZUfTR57hSEhZKUhglLW1zWvWXZ/+2BqvoGPrPNq2Ox7Btwzta0knncjIiZTVqbuS5T0xd/dwwVwJkLXPkXre3ZTlKQoq1eVt8MDyFAgxE0Lb+Z35AlowmBETLDLm6e09i9lQqumOwNgUq2oqOENWfTaXL1y10Kf4lsZZqnMqv+GoYsqCCqCerd4gZWBxBgwMCnO5tByGeKGF5I8DpdbGjKkyivE1iqU70rdwVSFVVOuXF3uOG/L7jlzXHCJD7lE//iCZ5ddWutI8BU7LPKrbTcOTiL6Lc6EtdhdT2WJqq71dVnNpaiD0NoK2vGdwhRNz8dmPUgUu/uAhov52Y7tUrJL1rYXqRnnzt1xq81TPhtbFqgT7JL/P2aAuTBXD6Kl5A8nfAn/ec2HAzGBWsGKhlFVqTLzALXLWJUiqc0D/eXvlVN7RSx4O7vfCk9ZQ0F6F/wr0FtJ2Oqy8HjRlowck+ZeGTDwE/TbzlwRa7OlcAD5qjaV4rsQNtpurErUEThDUNMaCDsL+/wvtCVqNlU/J2wb/Y42XEO/BjukMZxg0F59Xn2WQ=
